#!/bin/bash
src=$1
dst=$2

if [ -z "$1" ]; then
	for src in *.xml*; do
		python "$(dirname "$0")"/src/xml2yml.py -i $src
	done
elif [ -z "$2" ]; then
	python "$(dirname "$0")"/src/xml2yml.py -i $src
else
	python "$(dirname "$0")"/src/xml2yml.py -i $src -o $dst
fi
